apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argocdproj.io/sync-options: Prune=true
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx:1.25.2
        name: myapp
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
