apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.25.2
        name: nginx
	resources:
	  requests:
	    cpu: 25m
	    memory: 25Mi
	  limits:
	    cpu: 100m
	    memory: 256Mi
